version: 2

jobs:
  cook_scheduler_unit_tests:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    steps:
      - checkout
      - run: cd scheduler && lein test :all-but-benchmark
  
  cook_scheduler_build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    steps:
      - checkout
      - run: cd scheduler && lein uberjar

workflows:
  version: 2
  build_and_test:
    jobs:
      - cook_scheduler_unit_tests:
          filters:
            branches:
              only: circleci

      - cook_scheduler_build:
          filters:
            branches:
              only: circleci
