version: 2

jobs:
  cook_scheduler_and_job_client_unit_tests:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: cd scheduler && TRAVIS_BUILD_DIR=.. ./travis/setup.sh
      - run: pushd ../jobclient && mvn test
      - run: popd && lein with-profile +test test :all-but-benchmark
  
  cook_scheduler_integration_tests_with_http_basic_auth:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      - run: mkdir ~/bin && mv lein ~/bin && chmod a+x ~/bin/lein
      - run: echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run: cd integration && TRAVIS_BUILD_DIR=.. ./travis/prepare_integration.sh
      - run: ./travis/run_integration.sh --auth=http-basic

workflows:
  version: 2
  build_and_test:
    jobs:
      - cook_scheduler_and_job_client_unit_tests:
          filters:
            branches:
              only: circleci
      - cook_scheduler_integration_tests_with_http_basic_auth:
          filters:
            branches:
              only: circleci
