version: 2

jobs:
  java_job_client:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - run: cd jobclient && mvn install
      - run: mkdir -p workspace 
      - run: cp -r ${HOME}/.m2/repository/twosigma/cook-jobclient/ workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - cook-jobclient

  cook_scheduler_unit_tests:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -r /tmp/workspace/cook-jobclient/ ${HOME}/.m2/repository/twosigma/
      - run: cd scheduler && lein test :all-but-benchmark
  
  cook_scheduler_build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    steps:
      - checkout
      - run: cd scheduler && lein uberjar

workflows:
  version: 2
  build_and_test:
    jobs:
      - java_job_client:
          filters:
            branches:
              only: circleci

      - cook_scheduler_unit_tests:
          requires:
            - java_job_client
          filters:
            branches:
              only: circleci

      - cook_scheduler_build:
          filters:
            branches:
              only: circleci
